[package]
name = "makeup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-recursion = "1.0.0"
async-trait = "0.1.58"
either = "1.8.0"
eyre = "0.6.8"
futures-util = "0.3.25"
rand = "0.8.5"
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["full"] }
libc = "0.2.137"
fnv = "1.0.7"

[dependencies.makeup-ansi]
path = "../makeup-ansi"
