[package]
name = "makeup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-recursion = "1.0.0"
async-trait = "0.1.58"
dashmap = "5.4.0"
eyre = "0.6.8"
futures-util = "0.3.25"
tokio = { version = "1.21.2", features = ["full"] }
