[package]
name = "makeup"
description = "Stylish CLIs/TUIs for Rust!"
repository = "https://github.com/queer/makeup"
license = "MIT"
version = "0.0.4"
edition = "2021"
readme = "../README.md"
categories = ["command-line-interface", "rendering", "rendering::engine"]
keywords = ["cli", "tui", "terminal", "color", "60fps"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-recursion = "1.0.0"
async-trait = "0.1.58"
either = "1.8.0"
eyre = "0.6.8"
futures-util = "0.3.25"
rand = "0.8.5"
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["full"] }
libc = "0.2.137"
fnv = "1.0.7"

[dev-dependencies]
colorgrad = "0.6.2"

[dependencies.makeup-ansi]
path = "../makeup-ansi"
version = "0.0.2"

[dependencies.makeup-console]
path = "../makeup-console"
version = "0.0.3"
