[package]
name = "makeup-console"
description = "Console helper library for makeup"
repository = "https://github.com/queer/makeup"
license = "MIT"
version = "0.0.3"
edition = "2021"
categories = ["command-line-interface"]
keywords = ["console"]

[dependencies]
tokio = { version = "1.26.0", features = ["full"] }
eyre = "0.6.8"
nix = "0.26.2"
libc = "0.2.139"
async-recursion = "1.0.2"
thiserror = "1.0.38"

[dependencies.makeup-ansi]
path = "../makeup-ansi"
version = "0.0.2"
