[package]
name = "makeup-console"
description = "Console helper library for makeup"
repository = "https://github.com/queer/makeup"
license = "MIT"
version = "0.0.3"
edition = "2021"
categories = ["command-line-interface"]
keywords = ["console"]

[dependencies]
tokio = { version = "1.21.2", features = ["full"] }
eyre = "0.6.8"
nix = "0.25.0"
libc = "0.2.137"
async-recursion = "1.0.0"
thiserror = "1.0.37"

[dependencies.makeup-ansi]
path = "../makeup-ansi"
version = "0.0.2"
