name: "Test CLI functionality"
on:
  push:
    branches:
      - "mistress"
    paths:
    - "**.rs"
    - "test/**"
    - "there-cli/**"
  pull_request:
    branches:
      - "mistress"
    paths:
    - "**.rs"
    - "test/**"
    - "there-cli/**"

jobs:
  run-tests:
    strategy:
      matrix:
        version: ["stable", "nightly", "1.65"]
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: "Make sure SSH will work as expected"
        run: |
          ssh-keygen -t ed25519 -f ~/.ssh/whatever -N ''
          echo -n 'from="127.0.0.1" ' | cat - ~/.ssh/whatever.pub > ~/.ssh/authorized_keys
          chmod og-rw ~
      - name: "Install latest stable Rust"
        uses: "actions-rs/toolchain@v1"
        with:
          toolchain: "${{ matrix.version }}"
          override: true
      - uses: "Swatinem/rust-cache@v1"
        with:
          key: "clippy"
      - name: "Make sure the CLI passes valid config"
        run: "cargo run -p there-cli -- plan validate -f ./test/ci/plan.yaml --hosts ./test/ci/hosts.yaml"
      - name: "Make sure the CLI fails invalid config"
        run: "cargo run -p there-cli -- plan validate -f ./test/ci/invalid-plan.yaml --hosts ./test/ci/hosts.yaml || true"
      - name: "Make sure that the CLI can run basic configs"
        run: "cargo run -p there-cli -- plan apply -f ./test/ci/plan.yaml --hosts ./test/ci/hosts.yaml"
      # - name: "Make sure that the CLI can run SSH configs"
      #   run: "cargo run -p there-cli -- plan apply -f ./test/ci/ssh-plan.yaml --hosts ./test/ci/ssh-hosts.yaml --ssh-key /home/runner/.ssh/id_rsa && sleep 5" # TODO: Figure out why sleep(1) needed here
